name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: # Specify your branches here
      - main # The 'main' branch

jobs:
  qodana-and-build:
    runs-on: windows-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    env:
      DOTNET_VERSION: '9.0.3xx'
      DOTNET_QUALITY: 'ga'
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      - name: Install .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          dotnet-quality: ${{ env.DOTNET_QUALITY }}
          
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@main
        continue-on-error: true
        with:
          args: --ide,QDNET
          pr-mode: false
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_239419487 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'

      - uses: github/codeql-action/upload-sarif@v3
        if: always()
        continue-on-error: true
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        continue-on-error: true
        with:
          name: Hi3Helper.Plugin.HBR_${{ github.sha }}
          path: .\Hi3Helper.Plugin.HBR\publish\Release\
          compression-level: 9
